/*
 * Development seed. Idempotent (upserts by slug/email) so it can be re-run.
 *
 *   npx prisma migrate dev          # runs this automatically (see prisma.config.ts)
 *   npx tsx prisma/seed.ts          # or run it directly
 *
 * Seeds licenses, the five top-level categories, one product per category type
 * (so every admin/storefront path has data), and an EDITOR user for verifying
 * the role-gated admin. Embeddings are intentionally left null, they are
 * generated by the Voyage job in Stage 6.
 */
import { existsSync } from "node:fs";
import path from "node:path";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

try {
  process.loadEnvFile(".env.local");
} catch {
  try {
    process.loadEnvFile(".env");
  } catch {
    /* rely on ambient env */
  }
}

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error("DATABASE_URL is required to seed. Set it in .env.local.");
}

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString }),
});

async function main() {
  const standard = await prisma.license.upsert({
    where: { slug: "standard" },
    update: {},
    create: {
      slug: "standard",
      name: "Genesis Standard License",
      summary: "Royalty-free use in unlimited commercial projects; no resale.",
    },
  });

  const categories = [
    { slug: "game-assets", name: "Game Assets", sortOrder: 1 },
    { slug: "environment-kits", name: "Environment Kits", sortOrder: 2 },
    { slug: "procedural-tools", name: "Procedural Tools", sortOrder: 3 },
    { slug: "courses", name: "Courses", sortOrder: 4 },
    { slug: "bundles", name: "Bundles", sortOrder: 5 },
  ];
  const cat: Record<string, string> = {};
  for (const c of categories) {
    const row = await prisma.category.upsert({
      where: { slug: c.slug },
      update: { name: c.name, sortOrder: c.sortOrder },
      create: c,
    });
    cat[c.slug] = row.id;
  }

  // 1) Game asset
  await prisma.product.upsert({
    where: { slug: "sci-fi-supply-crate" },
    update: {},
    create: {
      slug: "sci-fi-supply-crate",
      type: "GAME_ASSET",
      status: "PUBLISHED",
      publishedAt: new Date(),
      title: "Sci-Fi Supply Crate",
      shortDesc: "Game-ready PBR crate with LODs.",
      categoryId: cat["game-assets"],
      licenseId: standard.id,
      priceCents: 1900,
      industry: "Games",
      theme: "Sci-Fi",
      style: "Realistic",
      includedInTier: "PRO",
      gameAssetDetail: {
        create: {
          polycount: 8200,
          isPbr: true,
          lodCount: 3,
          textureResMax: 4096,
          fileFormats: ["fbx", "glb", "obj"],
          targetEngines: ["Unreal", "Unity"],
          software: ["Blender", "Substance Painter"],
        },
      },
    },
  });

  // 2) Environment kit
  await prisma.product.upsert({
    where: { slug: "ww2-french-village-kit" },
    update: {},
    create: {
      slug: "ww2-french-village-kit",
      type: "ENVIRONMENT_KIT",
      status: "PUBLISHED",
      publishedAt: new Date(),
      title: "WW2 French Village Kit",
      shortDesc: "Modular war-torn village environment.",
      categoryId: cat["environment-kits"],
      licenseId: standard.id,
      priceCents: 12900,
      industry: "Film & VFX",
      theme: "WW2",
      style: "Realistic",
      includedInTier: "STUDIO",
      environmentKitDetail: {
        create: {
          moduleCount: 64,
          isModular: true,
          coverageAreaM2: 40000,
          biome: "temperate",
          fileFormats: ["fbx", "glb"],
          targetEngines: ["Unreal"],
          software: ["Houdini"],
        },
      },
    },
  });

  // 3) Procedural tool (with a parameter manifest powering the configurator)
  await prisma.product.upsert({
    where: { slug: "modular-wall-generator" },
    update: {},
    create: {
      slug: "modular-wall-generator",
      type: "PROCEDURAL_TOOL",
      status: "PUBLISHED",
      publishedAt: new Date(),
      title: "Modular Wall Generator",
      shortDesc: "Houdini HDA for parametric fortifications.",
      categoryId: cat["procedural-tools"],
      licenseId: standard.id,
      priceCents: 4900,
      industry: "Games",
      theme: "Historical",
      style: "Realistic",
      proceduralToolDetail: {
        create: {
          hostSoftware: "Houdini",
          toolType: "HDA",
          parameterManifest: {
            height: { type: "number", min: 1, max: 12, default: 3 },
            moduleCount: { type: "number", min: 1, max: 40, default: 8 },
            weathering: { type: "number", min: 0, max: 1, default: 0.3 },
            palette: {
              type: "enum",
              options: ["sandstone", "concrete", "brick"],
              default: "concrete",
            },
          },
        },
      },
    },
  });

  // 4) Course (curriculum is materialized later from `courseCurricula`)
  const courseFull =
    "Build a war-torn village from an empty scene to an engine-ready kit. " +
    "We start with procedural layout in Houdini, scatter and damage modules, " +
    "then export and assemble in-engine. Every chapter ends with a short quiz " +
    "so you can prove the concept stuck before moving on.";
  await prisma.product.upsert({
    where: { slug: "procedural-environments-101" },
    update: { fullDesc: courseFull },
    create: {
      slug: "procedural-environments-101",
      type: "COURSE",
      status: "PUBLISHED",
      publishedAt: new Date(),
      title: "Procedural Environments 101",
      shortDesc: "Build a war-torn village from scratch in Houdini.",
      fullDesc: courseFull,
      categoryId: cat["courses"],
      licenseId: standard.id,
      priceCents: 9900,
      industry: "Games",
      theme: "WW2",
      style: "Realistic",
    },
  });

  // 4b) Two more course mockups so the catalog grid reads like a real academy.
  await prisma.product.upsert({
    where: { slug: "blender-hard-surface-foundations" },
    update: {},
    create: {
      slug: "blender-hard-surface-foundations",
      type: "COURSE",
      status: "PUBLISHED",
      publishedAt: new Date(),
      title: "Blender Hard-Surface Foundations",
      shortDesc: "Model and bake a game-ready sci-fi prop, start to finish.",
      fullDesc:
        "A focused, project-based intro to hard-surface modelling in Blender: " +
        "blockout, subdivision and boolean workflows, high-to-low baking, and a " +
        "clean PBR handoff to your engine of choice.",
      categoryId: cat["courses"],
      licenseId: standard.id,
      priceCents: 6900,
      discountCents: 4900,
      industry: "Games",
      theme: "Sci-Fi",
      style: "Stylized",
      includedInTier: "PRO",
    },
  });
  await prisma.product.upsert({
    where: { slug: "unreal-environment-art-pipeline" },
    update: {},
    create: {
      slug: "unreal-environment-art-pipeline",
      type: "COURSE",
      status: "PUBLISHED",
      publishedAt: new Date(),
      title: "Unreal Environment Art Pipeline",
      shortDesc: "Assemble modular kits into a lit, optimized UE5 scene.",
      fullDesc:
        "Take a modular kit and build a believable environment in Unreal Engine 5: " +
        "set dressing, Nanite and Lumen, master materials, and performance passes " +
        "that keep your scene shippable.",
      categoryId: cat["courses"],
      licenseId: standard.id,
      priceCents: 0,
      industry: "Games",
      theme: "Sci-Fi",
      style: "Realistic",
    },
  });

  // 5) Bundle (published, with members) — buyers get an entitlement to each
  // member when they purchase it (entitlements fan out in payments/fulfillment).
  const bundle = await prisma.product.upsert({
    where: { slug: "ww2-starter-bundle" },
    update: { status: "PUBLISHED", publishedAt: new Date() },
    create: {
      slug: "ww2-starter-bundle",
      type: "BUNDLE",
      status: "PUBLISHED",
      publishedAt: new Date(),
      title: "WW2 Starter Bundle",
      shortDesc: "Kit + tool + course to launch a WW2 project.",
      categoryId: cat["bundles"],
      licenseId: standard.id,
      priceCents: 19900,
      industry: "Games",
      theme: "WW2",
      style: "Realistic",
    },
  });

  const bundleMemberSlugs = [
    "ww2-french-village-kit",
    "modular-wall-generator",
    "procedural-environments-101",
  ];
  for (const memberSlug of bundleMemberSlugs) {
    const member = await prisma.product.findUnique({
      where: { slug: memberSlug },
      select: { id: true },
    });
    if (member) {
      await prisma.bundleItem.upsert({
        where: {
          bundleId_memberId: { bundleId: bundle.id, memberId: member.id },
        },
        create: { bundleId: bundle.id, memberId: member.id },
        update: {},
      });
    }
  }

  // ── Course curricula ──────────────────────────────────────────────────────
  // Real Creative-Commons Blender open-movie video ids, so lessons actually play
  // in the LMS. Materialized idempotently: the Course row is upserted by product,
  // and chapters are only built when none exist yet, re-seeding a course that
  // already has a curriculum is a no-op, preserving any learner progress.
  type QType =
    | "MULTIPLE_CHOICE_SINGLE"
    | "MULTIPLE_CHOICE_MULTI"
    | "TRUE_FALSE"
    | "SHORT_ANSWER";
  type QSpec = {
    type: QType;
    prompt: string;
    options: { text: string; isCorrect: boolean }[];
  };
  type QuizSpec = {
    title: string;
    passingScore?: number;
    requiredToContinue?: boolean;
    questions: QSpec[];
  };
  type LessonSpec = {
    title: string;
    youtubeVideoId: string;
    durationSeconds: number;
  };
  type ChapterSpec = {
    title: string;
    lessons: LessonSpec[];
    quizzes?: QuizSpec[];
  };
  type CourseLevelSeed =
    | "BEGINNER"
    | "INTERMEDIATE"
    | "ADVANCED"
    | "ALL_LEVELS";
  type CourseMeta = {
    level?: CourseLevelSeed;
    estimatedTime?: string;
    releaseDate?: Date;
    prerequisites?: string;
    instructor?: string;
    instructorTitle?: string;
    software?: string[];
    outcomes?: string[];
    expectedRoi?: string;
  };
  type CourseSpec = {
    slug: string;
    summary: string;
    meta?: CourseMeta;
    chapters: ChapterSpec[];
  };

  const TF = (correct: "True" | "False"): QSpec["options"] => [
    { text: "True", isCorrect: correct === "True" },
    { text: "False", isCorrect: correct === "False" },
  ];

  const courseCurricula: CourseSpec[] = [
    {
      slug: "procedural-environments-101",
      summary: "From an empty scene to an engine-ready, war-torn village kit.",
      meta: {
        level: "INTERMEDIATE",
        estimatedTime: "6 weeks · 5 hrs/week",
        releaseDate: new Date("2026-02-10"),
        prerequisites:
          "Comfort navigating a 3D DCC. No prior Houdini or procedural experience required.",
        instructor: "Mara Castillo",
        instructorTitle: "Lead Environment Artist, Genesis",
        software: ["Houdini", "Unreal Engine 5", "Substance Painter"],
        outcomes: [
          "Lay out a believable village procedurally instead of by hand",
          "Scatter, damage, and vary modules for natural-looking wear",
          "Export an immutable, versioned kit",
          "Assemble and light the kit in Unreal Engine 5",
        ],
        expectedRoi:
          "Finish with a portfolio-ready environment and a reusable procedural pipeline you can point at any new project.",
      },
      chapters: [
        {
          title: "Foundations of Procedural Layout",
          lessons: [
            { title: "Why procedural?", youtubeVideoId: "aqz-KE-bpKQ", durationSeconds: 596 },
            { title: "Setting up your Houdini scene", youtubeVideoId: "eRsGyueVLvQ", durationSeconds: 888 },
          ],
          quizzes: [
            {
              title: "Chapter 1, Concepts check",
              requiredToContinue: true,
              questions: [
                {
                  type: "MULTIPLE_CHOICE_SINGLE",
                  prompt: "What is the primary advantage of a procedural workflow?",
                  options: [
                    { text: "Cheaper, faster iteration", isCorrect: true },
                    { text: "Smaller texture files", isCorrect: false },
                    { text: "It removes the need for an engine", isCorrect: false },
                  ],
                },
                {
                  type: "TRUE_FALSE",
                  prompt: "Procedural systems let you regenerate variations without re-modelling by hand.",
                  options: TF("True"),
                },
              ],
            },
          ],
        },
        {
          title: "Scatter, Damage & Variation",
          lessons: [
            { title: "Scattering modules", youtubeVideoId: "R6MlUcmOul8", durationSeconds: 734 },
            { title: "Adding weathering and damage", youtubeVideoId: "TLkA0RELQ1g", durationSeconds: 654 },
          ],
          quizzes: [
            {
              title: "Chapter 2, Variation check",
              questions: [
                {
                  type: "MULTIPLE_CHOICE_MULTI",
                  prompt: "Which are good sources of believable variation? (select all)",
                  options: [
                    { text: "Random rotation & scale", isCorrect: true },
                    { text: "Edge wear masks", isCorrect: true },
                    { text: "Using one identical mesh everywhere", isCorrect: false },
                    { text: "Color/material jitter", isCorrect: true },
                  ],
                },
                {
                  type: "SHORT_ANSWER",
                  prompt: "Name the node used to randomly place copies across a surface (one word).",
                  options: [
                    { text: "scatter", isCorrect: true },
                    { text: "scatter node", isCorrect: true },
                  ],
                },
              ],
            },
          ],
        },
        {
          title: "Export & Engine Assembly",
          lessons: [
            { title: "Exporting your kit", youtubeVideoId: "WhWc3b3KhnY", durationSeconds: 464 },
            { title: "Assembling in-engine", youtubeVideoId: "Y-rmzh0PI3c", durationSeconds: 728 },
          ],
          quizzes: [
            {
              title: "Final assessment",
              passingScore: 60,
              questions: [
                {
                  type: "MULTIPLE_CHOICE_SINGLE",
                  prompt: "Why keep each version's export as an immutable file?",
                  options: [
                    { text: "So older projects keep working unchanged", isCorrect: true },
                    { text: "To save disk space", isCorrect: false },
                    { text: "Engines require it", isCorrect: false },
                  ],
                },
                {
                  type: "TRUE_FALSE",
                  prompt: "A modular kit should snap cleanly on a consistent grid.",
                  options: TF("True"),
                },
              ],
            },
          ],
        },
      ],
    },
    {
      slug: "blender-hard-surface-foundations",
      summary: "Model and bake a game-ready sci-fi prop, start to finish.",
      meta: {
        level: "BEGINNER",
        estimatedTime: "4 weeks · 4 hrs/week",
        releaseDate: new Date("2025-11-18"),
        prerequisites: "None. Blender is free, we install it together in lesson one.",
        instructor: "Dev Okonkwo",
        instructorTitle: "Hard-Surface Artist",
        software: ["Blender", "Substance Painter"],
        outcomes: [
          "Block out a prop and refine proportions before detailing",
          "Use non-destructive boolean and subdivision workflows",
          "Bake high-to-low normals cleanly",
          "Hand off a tidy PBR set to any engine",
        ],
        expectedRoi:
          "Walk away with one finished, engine-ready prop and a repeatable hard-surface workflow for your reel.",
      },
      chapters: [
        {
          title: "Blockout & Booleans",
          lessons: [
            { title: "Blockout fundamentals", youtubeVideoId: "aqz-KE-bpKQ", durationSeconds: 596 },
            { title: "Boolean workflows", youtubeVideoId: "eRsGyueVLvQ", durationSeconds: 888 },
          ],
          quizzes: [
            {
              title: "Modelling check",
              questions: [
                {
                  type: "MULTIPLE_CHOICE_SINGLE",
                  prompt: "What is a blockout for?",
                  options: [
                    { text: "Establishing proportions before detailing", isCorrect: true },
                    { text: "Final UV unwrapping", isCorrect: false },
                    { text: "Baking normals", isCorrect: false },
                  ],
                },
                {
                  type: "SHORT_ANSWER",
                  prompt: "Which modifier non-destructively rounds hard edges? (one word)",
                  options: [{ text: "bevel", isCorrect: true }],
                },
              ],
            },
          ],
        },
        {
          title: "Baking & PBR Handoff",
          lessons: [
            { title: "High-to-low baking", youtubeVideoId: "R6MlUcmOul8", durationSeconds: 734 },
          ],
          quizzes: [
            {
              title: "Baking check",
              questions: [
                {
                  type: "TRUE_FALSE",
                  prompt: "A normal map lets a low-poly mesh read like a high-poly one.",
                  options: TF("True"),
                },
              ],
            },
          ],
        },
      ],
    },
    {
      slug: "unreal-environment-art-pipeline",
      summary: "Assemble modular kits into a lit, optimized UE5 scene.",
      meta: {
        level: "ADVANCED",
        estimatedTime: "8 weeks · 6 hrs/week",
        releaseDate: new Date("2026-04-01"),
        prerequisites:
          "Working knowledge of a modular kit and basic Unreal navigation.",
        instructor: "Mara Castillo",
        instructorTitle: "Lead Environment Artist, Genesis",
        software: ["Unreal Engine 5", "Blender"],
        outcomes: [
          "Set dress a modular kit into a believable scene",
          "Light with Lumen and scale geometry with Nanite",
          "Author master materials and instances",
          "Run performance passes that keep the scene shippable",
        ],
        expectedRoi:
          "Ship a lit, optimized UE5 environment that demonstrates production-level judgment to studios.",
      },
      chapters: [
        {
          title: "Set Dressing & Modularity",
          lessons: [
            { title: "Importing your kit", youtubeVideoId: "TLkA0RELQ1g", durationSeconds: 654 },
            { title: "Set dressing principles", youtubeVideoId: "WhWc3b3KhnY", durationSeconds: 464 },
          ],
          quizzes: [
            {
              title: "Composition check",
              questions: [
                {
                  type: "MULTIPLE_CHOICE_MULTI",
                  prompt: "Which help a scene read as believable? (select all)",
                  options: [
                    { text: "Varied silhouette & scale", isCorrect: true },
                    { text: "Intentional focal points", isCorrect: true },
                    { text: "Uniform spacing everywhere", isCorrect: false },
                  ],
                },
              ],
            },
          ],
        },
        {
          title: "Lighting & Optimization",
          lessons: [
            { title: "Lumen & Nanite in practice", youtubeVideoId: "Y-rmzh0PI3c", durationSeconds: 728 },
          ],
          quizzes: [
            {
              title: "Performance check",
              questions: [
                {
                  type: "MULTIPLE_CHOICE_SINGLE",
                  prompt: "What does Nanite primarily address?",
                  options: [
                    { text: "Rendering very high geometry efficiently", isCorrect: true },
                    { text: "Audio mixing", isCorrect: false },
                    { text: "Network replication", isCorrect: false },
                  ],
                },
                {
                  type: "TRUE_FALSE",
                  prompt: "Optimization passes should be left until after shipping.",
                  options: TF("False"),
                },
              ],
            },
          ],
        },
      ],
    },
  ];

  let chaptersBuilt = 0;
  for (const spec of courseCurricula) {
    const product = await prisma.product.findUnique({
      where: { slug: spec.slug },
      select: { id: true },
    });
    if (!product) continue;
    const meta = spec.meta ?? {};
    const courseData = {
      summary: spec.summary,
      level: meta.level ?? null,
      estimatedTime: meta.estimatedTime ?? null,
      releaseDate: meta.releaseDate ?? null,
      prerequisites: meta.prerequisites ?? null,
      instructor: meta.instructor ?? null,
      instructorTitle: meta.instructorTitle ?? null,
      software: meta.software ?? [],
      outcomes: meta.outcomes ?? [],
      expectedRoi: meta.expectedRoi ?? null,
    };
    const course = await prisma.course.upsert({
      where: { productId: product.id },
      update: courseData,
      create: { productId: product.id, ...courseData },
    });
    const existing = await prisma.chapter.count({
      where: { courseId: course.id },
    });
    if (existing > 0) continue; // already built, keep it idempotent

    for (let ci = 0; ci < spec.chapters.length; ci++) {
      const ch = spec.chapters[ci];
      const chapter = await prisma.chapter.create({
        data: { courseId: course.id, title: ch.title, sortOrder: ci },
      });
      await prisma.lesson.createMany({
        data: ch.lessons.map((l, li) => ({
          chapterId: chapter.id,
          title: l.title,
          youtubeVideoId: l.youtubeVideoId,
          durationSeconds: l.durationSeconds,
          sortOrder: li,
        })),
      });
      for (const qz of ch.quizzes ?? []) {
        await prisma.quiz.create({
          data: {
            chapterId: chapter.id,
            title: qz.title,
            passingScore: qz.passingScore ?? 70,
            requiredToContinue: qz.requiredToContinue ?? false,
            questions: {
              create: qz.questions.map((q, qi) => ({
                type: q.type,
                prompt: q.prompt,
                sortOrder: qi,
                options: {
                  create: q.options.map((o, oi) => ({
                    text: o.text,
                    isCorrect: o.isCorrect,
                    sortOrder: oi,
                  })),
                },
              })),
            },
          },
        });
      }
      chaptersBuilt++;
    }
  }

  // Product cover mockups. Each render lives at public/mockups/<slug>.jpg and is
  // wired as a THUMBNAIL (drives the browse card *and* the detail-page hero, since
  // it sorts first). Only wired when the file actually exists on disk, missing
  // renders fall back to the deterministic SchematicArt SVG rather than a broken
  // <img>. Delete-then-create keeps this idempotent across re-seeds.
  const mockups: Array<{ slug: string; alt: string }> = [
    { slug: "sci-fi-supply-crate", alt: "Sci-Fi Supply Crate, game-ready PBR render" },
    { slug: "ww2-french-village-kit", alt: "WW2 French Village Kit, modular environment render" },
    { slug: "modular-wall-generator", alt: "Modular Wall Generator, procedural wall variants" },
    { slug: "procedural-environments-101", alt: "Procedural Environments 101, course cover" },
    { slug: "blender-hard-surface-foundations", alt: "Blender Hard-Surface Foundations, course cover" },
    { slug: "unreal-environment-art-pipeline", alt: "Unreal Environment Art Pipeline, course cover" },
    { slug: "ww2-starter-bundle", alt: "WW2 Starter Bundle, collection render" },
  ];
  let wired = 0;
  for (const m of mockups) {
    const file = path.join(process.cwd(), "public", "mockups", `${m.slug}.jpg`);
    if (!existsSync(file)) continue;
    const product = await prisma.product.findUnique({
      where: { slug: m.slug },
      select: { id: true },
    });
    if (!product) continue;
    await prisma.productMedia.deleteMany({
      where: { productId: product.id, kind: "THUMBNAIL" },
    });
    await prisma.productMedia.create({
      data: {
        productId: product.id,
        kind: "THUMBNAIL",
        url: `/mockups/${m.slug}.jpg`,
        alt: m.alt,
        sortOrder: 0,
      },
    });
    wired++;
  }

  // EDITOR user for admin verification.
  await prisma.user.upsert({
    where: { email: "editor@genesis.forge" },
    update: { role: "EDITOR" },
    create: {
      email: "editor@genesis.forge",
      name: "Genesis Editor",
      role: "EDITOR",
    },
  });

  console.log(
    `Seed complete: licenses, categories, 7 products (3 courses), ` +
      `${chaptersBuilt} course chapter(s) built, 1 editor, ${wired} cover mockup(s) wired.`,
  );
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
